[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "1c8d95d744ce76bf3494832466bf5cf5d996e627"
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpich"
os = "linux"

    [[PETSc.download]]
    sha256 = "62991bbe18d6ee10749439c30b2f25e0a7795ad3ccf7844bf2528ac893868556"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.21.4+0/PETSc.v3.21.4.x86_64-linux-gnu-libgfortran4-mpi+mpich.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "dd29f6e448f93d4317c50d968a4066a6d1de1140"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[PETSc.download]]
    sha256 = "c149a23121887e17d9df0fa2355ec18dca0b2393968b802c95c7f105b9e59e6a"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.21.5+0/PETSc.v3.21.5.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "966e6f1215369b5121967a182203c3e1025e4b53"
libgfortran_version = "4.0.0"
mpi = "mpich"
os = "macos"

    [[PETSc.download]]
    sha256 = "b01711c2c837120698d0461c0b9e25f925902b8a2237aeb41222624651d516e6"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.21.5+0/PETSc.v3.21.5.x86_64-apple-darwin-libgfortran4-mpi+mpich.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "1f60b74977579a77a98696cbae9d13129f71a333"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[PETSc.download]]
    sha256 = "45553bba03a044cae6965f64565dbffc1df3262e3f103317ad1163864e59f257"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.21.5+0/PETSc.v3.21.5.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "4ae79962a72c310652325393a86588e6b9d5cb08"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[PETSc.download]]
    sha256 = "890889ae12c48088e79f9b479a75ca41bae01ef2974205eb517e34d72dd837f8"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.21.5+0/PETSc.v3.21.5.x86_64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "d399418b21a6a8894d4d3dfc8a4c1c19df27cf29"
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[PETSc.download]]
    sha256 = "7a574f45231a5b04bab82d4b50c527e6b2917d964f511fa7fa277c49f19f4d03"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.21.5+0/PETSc.v3.21.5.x86_64-w64-mingw32-libgfortran5-mpi+microsoftmpi.tar.gz"
