[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "1e30ad0acb6c26d12a990f173c5d6822bd8f78a5"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[PETSc.download]]
    sha256 = "4b451c208f9c0645e7023f42029e255b4d9ac1e30b0761ebc09ead2fab82861f"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.18.7+1/PETSc.v3.18.7.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "c49793c1cbb4ef38e12b3c7938ea15ee1a3a6a25"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[PETSc.download]]
    sha256 = "1b61f16a366a984b6e3a232f0c703c00a3944756b462973977019122492ead3d"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.19.6+0/PETSc.v3.19.6.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "e1e4d044087e44303ae0e2589d5a2fe9391cdb5b"
libgfortran_version = "4.0.0"
mpi = "mpich"
os = "macos"

    [[PETSc.download]]
    sha256 = "2a0d54fa54e58dbc9eb23734b0a2780135d2e8e66e6210133baf6756c5c7fd11"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.19.6+0/PETSc.v3.19.6.x86_64-apple-darwin-libgfortran4-mpi+mpich.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "214588931e0d3bb04177caa27036db1bd35e8055"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[PETSc.download]]
    sha256 = "abd948abdd8e73fc17e36983ada5d3dc4e41d6f76edade47fa453661ab160ee5"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.19.6+0/PETSc.v3.19.6.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "cc92756c19b7ee8140c09238eb7c278e8f86e6d7"
libgfortran_version = "4.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[PETSc.download]]
    sha256 = "7268a0942c3226211007b250efd716a73fc315da35bfbc29acd4730b73dfcc1f"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.19.6+0/PETSc.v3.19.6.x86_64-w64-mingw32-libgfortran4-mpi+microsoftmpi.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "99f96da6d6412c68b7cf2c4fc036d9c50ca86684"
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[PETSc.download]]
    sha256 = "013c1c95a681c444b54c2a1131b5d6422ead39c9c2e62406f6e95263950a1f52"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.19.6+0/PETSc.v3.19.6.x86_64-w64-mingw32-libgfortran5-mpi+microsoftmpi.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "97694d7c6a7cbdf98af788bfe1c025aba5006fb0"
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpich"
os = "linux"

    [[PETSc.download]]
    sha256 = "220e1be02d7e940267493ea37110d9db85985bc2c0bdba0dd91734754ce7ea1c"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.19.6+0/PETSc.v3.19.6.x86_64-linux-gnu-libgfortran4-mpi+mpich.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "b4824fa063e1d46b55a9760b77e4e4d797b08d80"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[PETSc.download]]
    sha256 = "f0a886b67f68dc5522db2805736ed27ae8c9ffd575aff6a4646826cbb9baaaec"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.19.6+0/PETSc.v3.19.6.x86_64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
