[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "1c8d95d744ce76bf3494832466bf5cf5d996e627"
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpich"
os = "linux"

    [[PETSc.download]]
    sha256 = "62991bbe18d6ee10749439c30b2f25e0a7795ad3ccf7844bf2528ac893868556"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.21.4+0/PETSc.v3.21.4.x86_64-linux-gnu-libgfortran4-mpi+mpich.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "966e6f1215369b5121967a182203c3e1025e4b53"
libgfortran_version = "4.0.0"
mpi = "mpich"
os = "macos"

    [[PETSc.download]]
    sha256 = "b01711c2c837120698d0461c0b9e25f925902b8a2237aeb41222624651d516e6"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.21.5+0/PETSc.v3.21.5.x86_64-apple-darwin-libgfortran4-mpi+mpich.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "40779a52ac8d68e2efff5be7101b01fed83e364f"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[PETSc.download]]
    sha256 = "39ac7c722a3c3cbe87e5db15b9c970915ba70f355f8ede1314b7e7e52d322bb8"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.22.0+0/PETSc.v3.22.0.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "2cfa62c65e0eebb77fb8c1465f7e2b69d5ccdfe4"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[PETSc.download]]
    sha256 = "dd82532a098bf7d906f24b81303458fa27ed0c2245768cbcd27ab830a79b1122"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.22.0+0/PETSc.v3.22.0.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "4d2bb4f87aca6487d10fe8bb1235fdc7c2406cbd"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[PETSc.download]]
    sha256 = "18274cdd085cbb53b87c1a3ca64afc06616994c5d77bd582394d5ad16f33e9fe"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.22.0+0/PETSc.v3.22.0.x86_64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "23b32adf9c393cf096ad85dc56f5bd1d90e7a232"
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[PETSc.download]]
    sha256 = "06f0184c2a0f095bdbc7d9925350b768a794666897734663a4f9163bb1440219"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.22.0+0/PETSc.v3.22.0.x86_64-w64-mingw32-libgfortran5-mpi+microsoftmpi.tar.gz"
