[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "4a5f5a168df7277e7119453bcc2f7b90263c9f9a"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[PETSc.download]]
    sha256 = "5e1eef03d40219bba523b356be7a9c9835671b278fb7af20c24e4441d1119cd2"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.20.0+0/PETSc.v3.20.0.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "9cfd475b51b0ca0214c7111bb47fb26577f99dc3"
libgfortran_version = "4.0.0"
mpi = "mpich"
os = "macos"

    [[PETSc.download]]
    sha256 = "3cf7233fe6e10d0efd3550e120f3c39e4343338b6f99ad85020f855bb3864b95"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.20.0+0/PETSc.v3.20.0.x86_64-apple-darwin-libgfortran4-mpi+mpich.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "706baa001dbdce2108ac2b1339e4cc8f47bb9ed9"
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpich"
os = "linux"

    [[PETSc.download]]
    sha256 = "43315848a0d5da9d4f190890f6c722e6cc83facd2ce65ac8dc60d08577eac659"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.20.0+0/PETSc.v3.20.0.x86_64-linux-gnu-libgfortran4-mpi+mpich.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "78798aa9e499475cfff2f3b179a7501dcde6364d"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[PETSc.download]]
    sha256 = "da982a01efbe816a448bccf68d39e0fcc0cb13029fd506402642e678e3637afb"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.20.0+0/PETSc.v3.20.0.x86_64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "60a7aaedf6bee6eb1cf48a82c7c7094272bc4f4f"
libgfortran_version = "4.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[PETSc.download]]
    sha256 = "1a57dc58b519d8ee2af72343b403c04198555d0e8b06c2190d242209a2770080"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.20.0+0/PETSc.v3.20.0.x86_64-w64-mingw32-libgfortran4-mpi+microsoftmpi.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "04229e47ad5fcb0028b05034a4522f00c082c48c"
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[PETSc.download]]
    sha256 = "58d5148eb4804b11ba4e5e77b0f7f243d01f3f0b78982764ac8c4e1d95db3d1f"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.20.0+0/PETSc.v3.20.0.x86_64-w64-mingw32-libgfortran5-mpi+microsoftmpi.tar.gz"
