[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "5183cd189a9cb9f5a67814c74d57a12dfd84f193"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[PETSc.download]]
    sha256 = "c1d66f461751a2ece441b6ec09487954538b5af1b156251de14058c532c85694"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.22.0+0/PETSc.v3.22.0.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "b2b61e14013356ba264f15d7bcebd0f42198a4cf"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[PETSc.download]]
    sha256 = "52fd7b98706a94cbd14d819f3379e2619783108365ad86d8aec773d9cc10befd"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.22.0+0/PETSc.v3.22.0.aarch64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
