[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "b2b61e14013356ba264f15d7bcebd0f42198a4cf"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[PETSc.download]]
    sha256 = "52fd7b98706a94cbd14d819f3379e2619783108365ad86d8aec773d9cc10befd"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.22.0+0/PETSc.v3.22.0.aarch64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "a92aff5f1a05fe73f6e311f303de0ba569cb2cd2"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[PETSc.download]]
    sha256 = "fd1f9ae0664c9e36b8b09eee27402d30d8c5c1fda9c62921e4b40d9e948b79bd"
    url = "https://github.com/boriskaus/PETSc_jll.jl/releases/download/PETSc-v3.22.0+0/PETSc.v3.22.0.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
