# Autogenerated wrapper script for PETSc_jll for aarch64-apple-darwin-libgfortran5-mpi+openmpi
export ex19, ex4, ex42, libpetsc, libpetsc_Float64_Real_Int64

using OpenBLAS32_jll
using SCALAPACK32_jll
using MPICH_jll
using CompilerSupportLibraries_jll
using OpenMPI_jll
JLLWrappers.@generate_wrapper_header("PETSc")
JLLWrappers.@declare_library_product(libpetsc, "@rpath/libpetsc_double_real_Int64_double_real_Int64.3.22.dylib")
JLLWrappers.@declare_library_product(libpetsc_Float64_Real_Int64, "@rpath/libpetsc_double_real_Int64_double_real_Int64.3.22.dylib")
JLLWrappers.@declare_executable_product(ex19)
JLLWrappers.@declare_executable_product(ex4)
JLLWrappers.@declare_executable_product(ex42)
function __init__()
    JLLWrappers.@generate_init_header(OpenBLAS32_jll, SCALAPACK32_jll, MPICH_jll, CompilerSupportLibraries_jll, OpenMPI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libpetsc,
        "lib/petsc/double_real_Int64/lib/libpetsc_double_real_Int64.3.22.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpetsc_Float64_Real_Int64,
        "lib/petsc/double_real_Int64/lib/libpetsc_double_real_Int64.3.22.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        ex19,
        "bin/ex19",
    )

    JLLWrappers.@init_executable_product(
        ex4,
        "bin/ex4",
    )

    JLLWrappers.@init_executable_product(
        ex42,
        "bin/ex42",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
