# Autogenerated wrapper script for PETSc_jll for x86_64-linux-gnu-libgfortran5-mpi+mpich
export ex4, ex42, libpetsc, libpetsc_Float64_Real_Int64

using OpenBLAS32_jll
using CompilerSupportLibraries_jll
using SuperLU_DIST_jll
using MUMPS_jll
using libblastrampoline_jll
using SCALAPACK32_jll
using METIS_jll
using SCOTCH_jll
using PARMETIS_jll
using MPICH_jll
JLLWrappers.@generate_wrapper_header("PETSc")
JLLWrappers.@declare_library_product(libpetsc, "libpetsc_double_real_Int64_double_real_Int64.so.3.18")
JLLWrappers.@declare_library_product(libpetsc_Float64_Real_Int64, "libpetsc_double_real_Int64_double_real_Int64.so.3.18")
JLLWrappers.@declare_executable_product(ex4)
JLLWrappers.@declare_executable_product(ex42)
function __init__()
    JLLWrappers.@generate_init_header(OpenBLAS32_jll, CompilerSupportLibraries_jll, SuperLU_DIST_jll, MUMPS_jll, libblastrampoline_jll, SCALAPACK32_jll, METIS_jll, SCOTCH_jll, PARMETIS_jll, MPICH_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libpetsc,
        "lib/petsc/double_real_Int64/lib/libpetsc_double_real_Int64.so.3.18",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpetsc_Float64_Real_Int64,
        "lib/petsc/double_real_Int64/lib/libpetsc_double_real_Int64.so.3.18",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        ex4,
        "bin/ex4",
    )

    JLLWrappers.@init_executable_product(
        ex42,
        "bin/ex42",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
