# Autogenerated wrapper script for PETSc_jll for x86_64-w64-mingw32-libgfortran4-mpi+microsoftmpi
export ex19, ex4, ex42, libpetsc, libpetsc_Float64_Real_Int64

using OpenBLAS32_jll
using CompilerSupportLibraries_jll
using SuiteSparse_jll
using SCALAPACK32_jll
using METIS_jll
using SCOTCH_jll
using PARMETIS_jll
JLLWrappers.@generate_wrapper_header("PETSc")
JLLWrappers.@declare_library_product(libpetsc, "libpetsc_double_real_Int64-3.18.6.dll")
JLLWrappers.@declare_library_product(libpetsc_Float64_Real_Int64, "libpetsc_double_real_Int64-3.18.6.dll")
JLLWrappers.@declare_executable_product(ex19)
JLLWrappers.@declare_executable_product(ex4)
JLLWrappers.@declare_executable_product(ex42)
function __init__()
    JLLWrappers.@generate_init_header(OpenBLAS32_jll, CompilerSupportLibraries_jll, SuiteSparse_jll, SCALAPACK32_jll, METIS_jll, SCOTCH_jll, PARMETIS_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libpetsc,
        "bin\\petsc\\double_real_Int64\\lib\\libpetsc_double_real_Int64-3.18.6.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpetsc_Float64_Real_Int64,
        "bin\\petsc\\double_real_Int64\\lib\\libpetsc_double_real_Int64-3.18.6.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        ex19,
        "bin\\ex19.exe",
    )

    JLLWrappers.@init_executable_product(
        ex4,
        "bin\\ex4.exe",
    )

    JLLWrappers.@init_executable_product(
        ex42,
        "bin\\ex42.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
